## Lab 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Read data

In [ ]:
names=[]
# Assign column names to the dataset
for i in range(1,257):
 names.append("feature_"+str(i))
labels=["label_1","label_2","label_3","label_4"]
names+=labels

# Read in the dataset
train_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab 1/DataSet/train.csv')
valid_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab 1/DataSet/valid.csv')
test_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Lab 1/DataSet/Test.csv')

In [ ]:
train_df.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0  -1.928826  -0.291540   1.105909   2.070652   0.657838  -0.670940   
1  -1.709277  -1.008998   0.956611   4.313823  -0.669455   1.928765   
2  -1.906183  -0.357562  -0.682627   4.651838  -0.884940   1.159512   
3   0.697872  -2.218567  -0.572214   1.192062   0.329554   0.741364   
4  -1.976895  -0.496308   0.368102   3.739787  -0.132058   1.234980   

   feature_7  feature_8  feature_9  feature_10  ...  feature_251  feature_252  \
0  -0.968238   0.049916   1.111149   -1.834592  ...    -0.691538    -1.152522   
1   0.162550   0.152173   2.356505   -2.898549  ...    -0.668235    -0.532695   
2   1.354481  -1.432248   2.160144   -3.175735  ...    -0.026728     0.440408   
3   0.962354   0.993512   2.896854   -1.600380  ...     0.709032     0.812106   
4  -0.501003   0.881554   1.630941   -3.853953  ...    -0.599700    -1.024829   

   feature_253  feature_254  feature_255  feature_256  label_1  label_2  \
0     0.441157    -1.494434    -0.344974    -0.395641       45      NaN   
1     0.151163    -1.876885     1.651534    -2.706490       45      NaN   
2     2.745906    -0.680754    -0.643588    -2.587203       45      NaN   
3     1.055266    -0.915258    -0.924856    -1.318964       45      NaN   
4     1.869753    -2.498570     3.268253    -1.356606       45      NaN   

   label_3  label_4  
0        1        6  
1        1        6  
2        1        6  
3        1        6  
4        1        6  

[5 rows x 260 columns]

In [ ]:
train_df.shape

(28520, 260)

In [ ]:
train_df.isnull().sum()

feature_1        0
feature_2        0
feature_3        0
feature_4        0
feature_5        0
              ... 
feature_256      0
label_1          0
label_2        480
label_3          0
label_4          0
Length: 260, dtype: int64

In [ ]:
valid_df.isnull().sum()

feature_1       0
feature_2       0
feature_3       0
feature_4       0
feature_5       0
               ..
feature_256     0
label_1         0
label_2        14
label_3         0
label_4         0
Length: 260, dtype: int64

In [ ]:
test_df.isnull().sum()

feature_1        0
feature_2        0
feature_3        0
feature_4        0
feature_5        0
              ... 
feature_256      0
label_1        750
label_2        750
label_3        750
label_4        750
Length: 260, dtype: int64

Scaling

In [ ]:
from sklearn.preprocessing import RobustScaler

x_train ={}
y_train ={}
x_valid ={}
y_valid ={}
x_test = {}

df_t = train_df
df_v = valid_df

for label in labels:
  scaler = RobustScaler()
  if label == 'label_2':
    df_t = train_df.dropna()
    df_v = valid_df.dropna()

  x_train[label] = scaler.fit_transform(df_t.drop(labels, axis=1))
  y_train[label] = df_t[label]
  x_valid[label] = scaler.transform(df_v.drop(labels, axis=1))
  y_valid[label] = df_v[label]
  x_test[label] = scaler.transform(test_df.drop(labels, axis=1))




In [ ]:
pd.DataFrame(x_train['label_2']).shape

(28040, 256)

##KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

def KNN(x_t,x_v,y_t):
  classifier = KNeighborsClassifier(n_neighbors=5)
  classifier.fit(x_t, y_t)

  y_pred = classifier.predict(x_v)
  return y_pred

  # print(confusion_matrix(y_v, y_pred))
  # print(classification_report(y_v, y_pred))

## SVM

In [ ]:
def SVM(x_t,x_v,y_t,y_v):
  svm_classifier = SVC(kernel='linear', class_weight='balanced')
  svm_classifier.fit(x_t, y_t)

  # Make predictions on the test data
  y_pred = svm_classifier.predict(x_v)

  # Evaluate model performance
  print(classification_report(y_v, y_pred))

## Regression

In [ ]:
from sklearn.linear_model import LinearRegression  # You can replace this with other regression algorithms
from sklearn.metrics import mean_squared_error, r2_score  # For evaluation
from sklearn.ensemble import RandomForestRegressor

def reg(x_t,x_v,y_t,y_v):
  regressor = LinearRegression()
  regressor.fit(x_t, y_t)

  y_pred = regressor.predict(x_v)

  mse = mean_squared_error(y_v, y_pred)
  r2 = r2_score(y_v, y_pred)

  print("Mean Squared Error:", mse)
  print("R-squared:", r2)

## Label 1

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train['label_1'], y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid['label_1'])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       1.00      1.00      1.00         9
           7       1.00      1.00      1.00        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.89      1.00      0.94         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

### Filter Method

In [ ]:
from sklearn.feature_selection import SelectKBest,f_classif

# scaler = RobustScaler()
# x_train_scaled = scaler.fit_transform(x_train[['label_1']])
# y_train_scaled = scaler.transform(y_train[['label_2']])

chi2_features = SelectKBest(f_classif, k=70)
x_kbest = chi2_features.fit_transform(x_train['label_1'], y_train['label_1'])

x_kbest.shape

(28520, 70)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_kbest, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(chi2_features.transform(x_valid['label_1']))

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[13  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 18  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        13
           2       0.90      1.00      0.95         9
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00        16
           5       0.95      1.00      0.97        18
           6       1.00      1.00      1.00         9
           7       1.00      1.00      1.00        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.73      1.00      0.84         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       0.92      1.00      0.96        11
          14       0.94      1.00      0.97        15
          15       1.00      1.00

### Estimator Model

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier  # You can replace this with any other model


In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train['label_1'], y_train['label_1'])  # Assuming x_train and y_train are your feature and target data


RandomForestClassifier()

In [ ]:
selector = SelectFromModel(model, threshold='mean')  # You can adjust the threshold as needed
x_train_selected = selector.fit_transform(x_train['label_1'], y_train['label_1'])

In [ ]:
x_train_selected.shape

(28520, 103)

In [ ]:
x_test_selected = selector.transform(x_valid['label_1'])  # Assuming x_test is your test data

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_selected, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test_selected)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       0.90      1.00      0.95         9
           7       1.00      1.00      1.00        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.80      1.00      0.89         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

In [ ]:
selector = SelectFromModel(model, threshold='median')  # You can adjust the threshold as needed
x_train_selected_2 = selector.fit_transform(x_train['label_1'], y_train['label_1'])

In [ ]:
x_train_selected_2.shape

(28520, 128)

In [ ]:
x_test_selected_2 = selector.transform(x_valid['label_1'])  # Assuming x_test is your test data

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_selected_2, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test_selected_2)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       0.90      1.00      0.95         9
           7       1.00      1.00      1.00        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.80      1.00      0.89         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

### Random Forest

In [ ]:
impotance = model.feature_importances_
final_df = pd.DataFrame({"Features":pd.DataFrame(x_train['label_1']).columns,"importance":impotance})
final_df.set_index('importance')
final_df_sorted = final_df.sort_values('importance')
final_df_sorted

Features  importance
4           4    0.002611
238       238    0.002618
30         30    0.002633
21         21    0.002655
158       158    0.002754
..        ...         ...
23         23    0.006860
231       231    0.006898
221       221    0.007377
232       232    0.007702
43         43    0.008431

[256 rows x 2 columns]

In [ ]:
# Get the indices of the least important features to remove
indices_to_remove = final_df_sorted["Features"][:202]

# Remove the least important features from the training dataset
X_train_removed = np.delete(x_train['label_1'], indices_to_remove, axis=1)
x_valid_removed = np.delete(x_valid['label_1'], indices_to_remove, axis=1)

In [ ]:
X_train_removed.shape

(28520, 54)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train_removed, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid_removed)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       0.92      0.92      0.92        13
           2       1.00      0.89      0.94         9
           3       0.80      1.00      0.89        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       0.90      1.00      0.95         9
           7       1.00      1.00      1.00        17
           8       0.93      1.00      0.97        14
           9       1.00      1.00      1.00        11
          10       0.80      1.00      0.89         8
          11       0.90      1.00      0.95        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

### PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.84, svd_solver="full")
pca.fit(x_train['label_1'])
x_train_pca = pca.transform(x_train['label_1'])
x_valid_pca = pca.transform(x_valid['label_1'])

In [ ]:
x_train_pca.shape

(28520, 37)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_pca, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid_pca)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[11  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      0.85      0.92        13
           2       1.00      1.00      1.00         9
           3       0.92      1.00      0.96        12
           4       1.00      1.00      1.00        16
           5       0.95      1.00      0.97        18
           6       1.00      1.00      1.00         9
           7       1.00      1.00      1.00        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.89      1.00      0.94         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       0.88      0.93      0.90        15
          15       1.00      1.00

In [ ]:
label_1_pred_before = KNN(x_train["label_1"],x_test['label_1'],y_train['label_1'])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
x_tets_pca = pca.transform(x_test['label_1'])
label_1_pred_after = classifier.predict(x_tets_pca)

pd.DataFrame(x_tets_pca)


0         1         2         3         4         5         6   \
0   -1.500508  5.167699 -2.679607 -1.251477 -4.766163 -1.009115  2.646372   
1   -5.185601  6.477794  0.066528 -7.786906 -3.425548  1.659710 -1.279572   
2   -3.655569  2.583212 -0.056895 -4.151993 -1.596252 -0.865812 -0.053392   
3   -1.665615  4.492834 -0.723284 -0.693712  1.638894  3.461804  0.222297   
4    0.310091  4.514874  1.348366 -2.426086 -2.180181 -0.866983  1.366032   
..        ...       ...       ...       ...       ...       ...       ...   
745  0.472381 -0.940024 -5.715502  3.065052  0.260611 -2.485517  0.507330   
746  8.421127  3.184758 -0.930040 -0.742543 -0.142731  0.486019  0.519685   
747 -4.104663  1.678485 -1.596858 -1.128760  1.334694  3.414412 -4.176270   
748 -3.391183  2.768467  2.498624  2.333551 -1.653734 -0.274364 -0.304824   
749  2.366818  2.071706 -2.925003  0.976219 -4.708499 -1.914967 -1.088126   

           7         8         9   ...        27        28        29  \
0    2.059013  4.486463  1.481350  ... -0.659240 -2.238538  1.203118   
1    1.855615 -2.025913  5.425406  ...  0.259978 -0.215138  0.162254   
2    0.049968 -4.426579  3.808164  ...  1.160343 -0.315466  1.025855   
3    0.470753  1.110993  4.823751  ...  1.303351 -2.371168  0.606335   
4    2.748820  0.603869  5.468676  ...  0.200779  0.956095  1.885016   
..        ...       ...       ...  ...       ...       ...       ...   
745 -2.754692 -1.054212  1.208389  ...  0.012224 -1.724243 -0.334600   
746 -1.169271 -0.275767 -1.740194  ...  1.124367  0.350932 -0.131597   
747 -1.710421 -0.688657 -0.214286  ... -0.837321  1.657879  0.832305   
748 -1.916929  2.581346 -2.323765  ...  0.613270 -0.298772  2.011881   
749 -0.073634  0.911300  0.581575  ... -0.286006 -1.171562 -1.389265   

           30        31        32        33        34        35        36  
0    0.790715  0.032765  2.000264  2.157813 -0.579622 -0.941363 -0.396000  
1    0.559397  0.108823 -0.771920  0.289616 -0.627237 -0.761139 -1.039271  
2    1.593888 -0.130312 -0.548878 -0.640456 -0.951691 -0.514799 -0.711533  
3    0.558340 -1.002022 -1.738454 -1.304003 -0.939968  0.192779 -1.716378  
4   -0.493400  0.552957 -1.029181  0.203553 -0.198968 -0.259912 -1.443620  
..        ...       ...       ...       ...       ...       ...       ...  
745  0.993278  0.236256  0.201985  1.300281  0.119619 -1.146856  0.148063  
746 -0.456930  2.102418  0.997167  1.314345  0.459685  0.659913 -0.182789  
747 -0.217676 -0.432318  1.682600  0.326617  0.764817  0.982816  0.862530  
748  3.357274  0.058312  0.325797  0.832059 -0.167548  0.718258 -2.395365  
749 -1.484005  0.122331  0.502410  1.154396  0.255722 -0.036411 -0.128858  

[750 rows x 37 columns]

In [ ]:
label1_features = pd.DataFrame(data=x_tets_pca, columns=[f'new_feature_{i+1}' for i in range(x_tets_pca.shape[1])])
label1_features.insert(0,'Predicted labels before feature engineering',label_1_pred_before)
label1_features.insert(1,'Predicted labels after feature engineering', label_1_pred_after)
label1_features.insert(2,'No of new features', x_tets_pca.shape[1])

In [ ]:
def write_csv(feature_df, label):
  for i in range(feature_df['No of new features'][0], 256):
        feature_df[f'new_feature_{i+1}'] = pd.NA
  filename = f'/content/drive/MyDrive/Colab Notebooks/Lab 1/DataSet/190200X_label_{label}.csv'
  feature_df.to_csv(filename,index=False)

In [ ]:
write_csv(label1_features,"label_1")

### Random Forest + PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.99, svd_solver="full")
pca.fit(X_train_removed)
x_train_pca = pca.transform(X_train_removed)
x_valid_pca = pca.transform(x_valid_removed)

In [ ]:
x_train_pca.shape

(28520, 46)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_pca, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid_pca)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[13  0  0 ...  0  0  0]
 [ 0  8  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 19  0  1]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       0.87      1.00      0.93        13
           2       1.00      0.89      0.94         9
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00        16
           5       0.95      1.00      0.97        18
           6       0.90      1.00      0.95         9
           7       0.94      1.00      0.97        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.80      1.00      0.89         8
          11       0.86      1.00      0.93        19
          12       1.00      1.00      1.00         7
          13       0.92      1.00      0.96        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

### Ridge

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge_reg = Ridge(alpha =1.0)
ridge_reg.fit(x_train['label_1'],y_train['label_1'])
coefs = ridge_reg.coef_
final_df = pd.DataFrame({"Features":pd.DataFrame(x_train['label_1']).columns,"coefs":coefs})
final_df.set_index('coefs')
final_df_sorted = final_df.sort_values('coefs')

In [ ]:
# Get the indices of the least important features to remove
indices_to_remove = final_df_sorted["Features"][:170]

# Remove the least important features from the training dataset
X_train_removed = np.delete(x_train['label_1'], indices_to_remove, axis=1)
x_valid_removed = np.delete(x_valid['label_1'], indices_to_remove, axis=1)

In [ ]:
X_train_removed.shape

(28520, 86)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train_removed, y_train['label_1'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid_removed)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_1'], y_pred))
print(classification_report(y_valid['label_1'], y_pred))

[[12  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0 12 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 10  0]
 [ 0  0  0 ...  0  0 10]]
              precision    recall  f1-score   support

           1       1.00      0.92      0.96        13
           2       1.00      1.00      1.00         9
           3       0.75      1.00      0.86        12
           4       1.00      1.00      1.00        16
           5       1.00      1.00      1.00        18
           6       1.00      1.00      1.00         9
           7       0.94      1.00      0.97        17
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       0.89      1.00      0.94         8
          11       0.95      1.00      0.97        19
          12       1.00      1.00      1.00         7
          13       1.00      1.00      1.00        11
          14       1.00      1.00      1.00        15
          15       1.00      1.00

## Label 2

In [ ]:
from sklearn.linear_model import LinearRegression  # You can replace this with other regression algorithms
from sklearn.metrics import mean_squared_error, r2_score  # For evaluation
from sklearn.ensemble import RandomForestRegressor


In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(x_train['label_2'], y_train['label_2'])


LinearRegression()

In [ ]:
y_pred = regressor.predict(x_valid['label_2'])

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 23.8255920404057
R-squared: 0.43851414716544457


In [ ]:
label_2_pred_before = regressor.predict(x_test['label_2'])

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score


# Create and train the Gradient Boosting Regressor
regressor = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
regressor.fit(x_train['label_2'], y_train['label_2'])

# Make predictions
y_pred = regressor.predict(x_valid['label_2'])

# Evaluate model performance
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 20.213011619939863
R-squared: 0.5236500294083161


### Filter Method

In [ ]:
from sklearn.feature_selection import SelectKBest,f_regression

# scaler = RobustScaler()
# x_train_scaled = scaler.fit_transform(x_train[['label_1']])
# y_train_scaled = scaler.transform(y_train[['label_2']])

chi2_features = SelectKBest(f_regression, k=200)
x_kbest = chi2_features.fit_transform(x_train['label_2'], y_train['label_2'])

x_kbest.shape

(28040, 200)

In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(x_kbest, y_train['label_2'])


LinearRegression()

In [ ]:
y_pred = regressor.predict(chi2_features.transform(x_valid['label_2']))

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 25.436027322168574
R-squared: 0.40056182152828956


### Estimator Model

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier  # You can replace this with any other model


In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train['label_2'], y_train['label_2'])  # Assuming x_train and y_train are your feature and target data


RandomForestClassifier()

In [ ]:
selector = SelectFromModel(model, threshold='mean')  # You can adjust the threshold as needed
x_train_selected = selector.fit_transform(x_train['label_2'], y_train['label_2'])

In [ ]:
x_train_selected.shape

(28040, 111)

In [ ]:
x_test_selected = selector.transform(x_valid['label_2'])  # Assuming x_test is your test data

In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(x_train_selected, y_train['label_2'])


LinearRegression()

In [ ]:
y_pred = regressor.predict(x_test_selected)

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 28.446777117686803
R-squared: 0.32960898166848174


In [ ]:
selector = SelectFromModel(model, threshold='median')  # You can adjust the threshold as needed
x_train_selected_2 = selector.fit_transform(x_train['label_2'], y_train['label_2'])

In [ ]:
x_train_selected_2.shape

(28040, 128)

In [ ]:
x_test_selected_2 = selector.transform(x_valid['label_2'])  # Assuming x_test is your test data

In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(x_train_selected_2, y_train['label_2'])


LinearRegression()

In [ ]:
y_pred = regressor.predict(x_test_selected_2)

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 28.10477354543721
R-squared: 0.3376688093995771


### Random Forest

In [ ]:
impotance = model.feature_importances_
final_df = pd.DataFrame({"Features":pd.DataFrame(x_train['label_2']).columns,"importance":impotance})
final_df.set_index('importance')
final_df_sorted = final_df.sort_values('importance')
final_df_sorted

Features  importance
47         47    0.002603
238       238    0.002662
251       251    0.002670
4           4    0.002684
207       207    0.002700
..        ...         ...
27         27    0.006559
188       188    0.006712
232       232    0.007459
221       221    0.007485
43         43    0.007798

[256 rows x 2 columns]

In [ ]:
# Get the indices of the least important features to remove
indices_to_remove = final_df_sorted["Features"][:140]

# Remove the least important features from the training dataset
X_train_removed = np.delete(x_train['label_2'], indices_to_remove, axis=1)
x_valid_removed = np.delete(x_valid['label_2'], indices_to_remove, axis=1)

In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(X_train_removed, y_train['label_2'])

LinearRegression()

In [ ]:
y_pred = regressor.predict(x_valid_removed)

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 27.98148384102135
R-squared: 0.34057431641540525


### PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.99, svd_solver="full")
pca.fit(x_train['label_2'])
x_train_pca = pca.transform(x_train['label_2'])
x_valid_pca = pca.transform(x_valid['label_2'])

In [ ]:
x_train_pca.shape

(28040, 106)

In [ ]:
regressor = LinearRegression()  # You can replace this with other regression algorithms
regressor.fit(x_train_pca, y_train['label_2'])


LinearRegression()

In [ ]:
y_pred = regressor.predict(x_valid_pca)

In [ ]:
mse = mean_squared_error(y_valid['label_2'], y_pred)
r2 = r2_score(y_valid['label_2'], y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 27.947551854937313
R-squared: 0.3413739746195942


In [ ]:
x_tets_pca = pca.transform(x_test['label_2'])
label_2_pred_after = regressor.predict(x_tets_pca)

pd.DataFrame(x_tets_pca)

0         1         2         3         4         5         6    \
0   -1.340205  4.974926 -2.463431 -0.293218 -4.929589 -0.123418  2.821178   
1   -4.916497  5.968590  0.216444  5.458443 -5.255487  3.739646 -0.946314   
2   -3.488105  2.233849 -0.015782  3.096022 -2.791336  0.041352 -0.145018   
3   -1.514295  4.172956 -0.653871  0.501919  2.118996  3.109811 -0.061919   
4    0.474417  4.185025  1.483051  1.486173 -2.755140 -0.114920  1.350989   
..        ...       ...       ...       ...       ...       ...       ...   
745  0.448947 -0.646220 -5.753660 -2.408283  0.738003 -3.273074  0.090460   
746  8.518059  3.102605 -0.863859  0.605481 -0.400065  0.875040  0.714044   
747 -4.120542  1.930092 -1.584527  1.149447  1.199155  3.698053 -4.019199   
748 -3.353879  2.953521  2.631003 -2.415959 -1.040848 -0.376159 -0.225274   
749  2.403618  2.169200 -2.802205 -2.172835 -4.548291 -1.379743 -1.034626   

          7         8         9    ...       96        97        98   \
0    1.792234  4.454589 -1.476093  ...  0.208509 -0.274583 -0.451363   
1    2.011677 -2.027165 -6.018996  ... -0.022700  0.589535  0.052991   
2    0.186335 -4.450069 -3.704063  ...  0.295798  0.306357  0.065416   
3    0.296568  1.147972 -4.216535  ... -0.147911  0.286405  0.361166   
4    2.659574  0.763504 -5.778474  ... -0.172220  0.258270 -0.026467   
..        ...       ...       ...  ...       ...       ...       ...   
745 -2.777527 -0.996790 -0.866410  ...  0.013069 -0.154438  0.016161   
746 -1.067262 -0.286181  1.480675  ...  0.283112 -0.049097 -0.267336   
747 -1.535927 -0.870620  0.250776  ...  0.211706  0.026253 -0.383232   
748 -2.048063  2.418676  2.822469  ... -0.084207  0.340817 -0.055687   
749 -0.010381  0.894225 -0.466329  ... -0.171230 -0.009358  0.115407   

          99        100       101       102       103       104       105  
0    0.230961  0.074313  0.147012 -0.702237  0.297049  0.264837 -0.080787  
1    0.005924  0.280238  0.394139 -0.014935 -0.116512 -0.105058 -0.231154  
2   -0.189945  0.014903 -0.122696 -0.216926  0.019179 -0.715185  0.093243  
3    0.178927  0.714029  0.541698  0.361302  0.147558  0.151032 -0.465786  
4   -0.230994 -0.114979 -0.025865  0.442617  0.128621 -0.066989  0.204249  
..        ...       ...       ...       ...       ...       ...       ...  
745 -0.276373  0.038584 -0.062504 -0.025251  0.072047 -0.068987  0.478160  
746 -0.238764  0.123454 -0.410610  0.228027  0.071662 -0.075674  0.475122  
747  0.337476 -0.450441  0.107531  0.350141  0.056679 -0.038525  0.023988  
748  0.327965 -1.024172  0.067515  0.237579 -0.300107  0.319717  0.581777  
749 -0.394181 -0.297965  0.230186 -0.036326  0.238619  0.577113  0.172433  

[750 rows x 106 columns]

In [ ]:
label2_features = pd.DataFrame(data=x_tets_pca, columns=[f'new_feature_{i+1}' for i in range(x_tets_pca.shape[1])])
label2_features.insert(0,'Predicted labels before feature engineering',label_2_pred_before)
label2_features.insert(1,'Predicted labels after feature engineering', label_2_pred_after)
label2_features.insert(2,'No of new features', x_tets_pca.shape[1])

In [ ]:
write_csv(label2_features,"label_2")

<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  feature_df[f'new_feature_{i+1}'] = pd.NA
<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  feature_df[f'new_feature_{i+1}'] = pd.NA
<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `new

## Label 3

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train['label_3'], y_train['label_3'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid['label_3'])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_3'], y_pred))
print(classification_report(y_valid['label_3'], y_pred))

[[141   1]
 [  0 594]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       142
           1       1.00      1.00      1.00       594

    accuracy                           1.00       736
   macro avg       1.00      1.00      1.00       736
weighted avg       1.00      1.00      1.00       736



In [ ]:
label_3_pred_before = classifier.predict(x_test['label_3'])

### Filter method

In [ ]:
from sklearn.feature_selection import SelectKBest,f_classif

# scaler = RobustScaler()
# x_train_scaled = scaler.fit_transform(x_train[['label_1']])
# y_train_scaled = scaler.transform(y_train[['label_2']])

chi2_features = SelectKBest(f_classif, k=19)
x_kbest = chi2_features.fit_transform(x_train['label_3'], y_train['label_3'])

x_kbest.shape

(28040, 19)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_kbest, y_train['label_3'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(chi2_features.transform(x_valid['label_3']))

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_3'], y_pred))
print(classification_report(y_valid['label_3'], y_pred))

[[142   0]
 [  3 591]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       142
           1       1.00      0.99      1.00       594

    accuracy                           1.00       736
   macro avg       0.99      1.00      0.99       736
weighted avg       1.00      1.00      1.00       736



### PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.55, svd_solver="full")
pca.fit(x_train['label_3'])
x_train_pca = pca.transform(x_train['label_3'])
x_valid_pca = pca.transform(x_valid['label_3'])

In [ ]:
x_train_pca.shape

(28040, 12)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train_pca, y_train['label_3'])

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_valid_pca)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_valid['label_3'], y_pred))
print(classification_report(y_valid['label_3'], y_pred))

[[142   0]
 [  3 591]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       142
           1       1.00      0.99      1.00       594

    accuracy                           1.00       736
   macro avg       0.99      1.00      0.99       736
weighted avg       1.00      1.00      1.00       736



In [ ]:
x_tets_pca = pca.transform(x_test['label_3'])
label_3_pred_after = classifier.predict(x_tets_pca)

pd.DataFrame(x_tets_pca)

0         1         2         3         4         5         6   \
0   -1.340205  4.974926 -2.463431 -0.293218 -4.929589 -0.123418  2.821178   
1   -4.916497  5.968590  0.216444  5.458443 -5.255487  3.739646 -0.946314   
2   -3.488105  2.233849 -0.015782  3.096022 -2.791336  0.041352 -0.145018   
3   -1.514295  4.172956 -0.653871  0.501919  2.118996  3.109811 -0.061919   
4    0.474417  4.185025  1.483051  1.486173 -2.755140 -0.114920  1.350989   
..        ...       ...       ...       ...       ...       ...       ...   
745  0.448947 -0.646220 -5.753660 -2.408283  0.738003 -3.273074  0.090460   
746  8.518059  3.102605 -0.863859  0.605481 -0.400065  0.875040  0.714044   
747 -4.120542  1.930092 -1.584527  1.149447  1.199155  3.698053 -4.019199   
748 -3.353879  2.953521  2.631003 -2.415959 -1.040848 -0.376159 -0.225274   
749  2.403618  2.169200 -2.802205 -2.172835 -4.548291 -1.379743 -1.034626   

           7         8         9         10        11  
0    1.792234  4.454589 -1.476093  3.161077  0.292941  
1    2.011677 -2.027165 -6.018996 -0.333028  0.583661  
2    0.186335 -4.450069 -3.704063  1.913868  0.410853  
3    0.296568  1.147972 -4.216535  2.493196 -2.456245  
4    2.659574  0.763504 -5.778474 -0.377765 -1.427959  
..        ...       ...       ...       ...       ...  
745 -2.777527 -0.996790 -0.866410 -0.818672  1.380985  
746 -1.067262 -0.286181  1.480675 -2.455038  0.871299  
747 -1.535927 -0.870620  0.250776  0.468023 -1.045527  
748 -2.048063  2.418676  2.822469  4.462614 -0.087807  
749 -0.010381  0.894225 -0.466329  2.470593  1.985181  

[750 rows x 12 columns]

In [ ]:
label3_features = pd.DataFrame(data=x_tets_pca, columns=[f'new_feature_{i+1}' for i in range(x_tets_pca.shape[1])])
label3_features.insert(0,'Predicted labels before feature engineering',label_3_pred_before)
label3_features.insert(1,'Predicted labels after feature engineering', label_3_pred_after)
label3_features.insert(2,'No of new features', x_tets_pca.shape[1])

In [ ]:
write_csv(label3_features,"label_3")

<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  feature_df[f'new_feature_{i+1}'] = pd.NA
<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  feature_df[f'new_feature_{i+1}'] = pd.NA
<ipython-input-66-b9b89ec60ecf>:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `new

## Label 4

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_classifier = SVC(kernel='linear', class_weight='balanced')
svm_classifier.fit(x_train['label_4'], y_train['label_4'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid['label_4'])

# Evaluate model performance
print(classification_report(y_valid['label_4'], y_pred))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78        21
           1       0.83      0.91      0.87        11
           2       0.65      0.96      0.78        27
           3       0.89      1.00      0.94         8
           4       0.88      1.00      0.94        15
           5       0.92      1.00      0.96        11
           6       0.99      0.92      0.96       518
           7       0.90      0.88      0.89        32
           8       0.95      1.00      0.97        19
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        10
          11       1.00      1.00      1.00        11
          12       0.74      0.88      0.81        26
          13       1.00      1.00      1.00        10

    accuracy                           0.93       736
   macro avg       0.89      0.97      0.92       736
weighted avg       0.95      0.93      0.94       736



In [ ]:
label_4_pred_before = svm_classifier.predict(x_test['label_4'])

### Random Forest

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier  # You can replace this with any other model


In [ ]:
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train['label_4'], y_train['label_4'])  # Assuming x_train and y_train are your feature and target data


RandomForestClassifier()

In [ ]:
impotance = model.feature_importances_
final_df = pd.DataFrame({"Features":pd.DataFrame(x_train['label_4']).columns,"importance":impotance})
final_df.set_index('importance')
final_df_sorted = final_df.sort_values('importance')
final_df_sorted

Features  importance
207       207    0.002208
47         47    0.002236
147       147    0.002290
238       238    0.002329
58         58    0.002381
..        ...         ...
35         35    0.007197
226       226    0.007386
82         82    0.007553
116       116    0.007607
98         98    0.011302

[256 rows x 2 columns]

In [ ]:
# Get the indices of the least important features to remove
indices_to_remove = final_df_sorted["Features"][:80]

# Remove the least important features from the training dataset
X_train_removed = np.delete(x_train['label_4'], indices_to_remove, axis=1)
x_test_remove =  np.delete(x_test['label_4'], indices_to_remove, axis=1)

In [ ]:
svm_classifier = SVC(kernel='linear', class_weight='balanced')
svm_classifier.fit(X_train_removed, y_train['label_4'])

# Make predictions on the test data
y_pred = svm_classifier.predict(np.delete(x_valid['label_4'], indices_to_remove, axis=1))

# Evaluate model performance
print(classification_report(y_valid['label_4'], y_pred))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75        21
           1       0.83      0.91      0.87        11
           2       0.60      0.96      0.74        27
           3       0.73      1.00      0.84         8
           4       0.94      1.00      0.97        15
           5       0.79      1.00      0.88        11
           6       0.99      0.89      0.94       518
           7       0.96      0.84      0.90        32
           8       0.90      0.95      0.92        19
           9       1.00      1.00      1.00        17
          10       0.91      1.00      0.95        10
          11       1.00      1.00      1.00        11
          12       0.60      0.96      0.74        26
          13       1.00      0.90      0.95        10

    accuracy                           0.91       736
   macro avg       0.85      0.96      0.89       736
weighted avg       0.94      0.91      0.92       736



j

### PCA

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components= 0.99, svd_solver="full")
pca.fit(x_train['label_4'])
x_train_pca = pca.transform(x_train['label_4'])
x_valid_pca = pca.transform(x_valid['label_4'])

In [ ]:
x_train_pca.shape

(28040, 106)

In [ ]:
svm_classifier = SVC(kernel='linear', class_weight='balanced')
svm_classifier.fit(x_train_pca, y_train['label_4'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid_pca)

# Evaluate model performance
print(classification_report(y_valid['label_4'], y_pred))

              precision    recall  f1-score   support

           0       0.47      0.86      0.61        21
           1       0.77      0.91      0.83        11
           2       0.52      0.96      0.68        27
           3       0.80      1.00      0.89         8
           4       0.79      1.00      0.88        15
           5       0.61      1.00      0.76        11
           6       0.98      0.83      0.90       518
           7       0.72      0.88      0.79        32
           8       0.90      1.00      0.95        19
           9       0.94      1.00      0.97        17
          10       0.77      1.00      0.87        10
          11       1.00      1.00      1.00        11
          12       0.56      0.88      0.69        26
          13       1.00      0.90      0.95        10

    accuracy                           0.86       736
   macro avg       0.77      0.94      0.84       736
weighted avg       0.90      0.86      0.87       736



### Filter Method

In [ ]:
from sklearn.feature_selection import SelectKBest,f_classif

# scaler = RobustScaler()
# x_train_scaled = scaler.fit_transform(x_train[['label_1']])
# y_train_scaled = scaler.transform(y_train[['label_2']])

chi2_features = SelectKBest(f_classif, k=190)
x_kbest = chi2_features.fit_transform(x_train['label_4'], y_train['label_4'])

x_kbest.shape

(28040, 190)

In [ ]:
svm_classifier = SVC(kernel='linear', class_weight='balanced')
svm_classifier.fit(x_train_pca, y_train['label_4'])

# Make predictions on the test data
y_pred = svm_classifier.predict(x_valid_pca)

# Evaluate model performance
print(classification_report(y_valid['label_4'], y_pred))

              precision    recall  f1-score   support

           0       0.47      0.86      0.61        21
           1       0.77      0.91      0.83        11
           2       0.52      0.96      0.68        27
           3       0.80      1.00      0.89         8
           4       0.79      1.00      0.88        15
           5       0.61      1.00      0.76        11
           6       0.98      0.83      0.90       518
           7       0.72      0.88      0.79        32
           8       0.90      1.00      0.95        19
           9       0.94      1.00      0.97        17
          10       0.77      1.00      0.87        10
          11       1.00      1.00      1.00        11
          12       0.56      0.88      0.69        26
          13       1.00      0.90      0.95        10

    accuracy                           0.86       736
   macro avg       0.77      0.94      0.84       736
weighted avg       0.90      0.86      0.87       736



In [ ]:
x_tets_pca = pca.transform(x_test['label_4'])
label_4_pred_after = svm_classifier.predict(x_test_remove)

pd.DataFrame(x_test_remove)

0         1         2         3         4         5         6    \
0   -0.724099  0.243082  1.478785 -1.424068  1.219783 -0.651757 -0.276519   
1   -1.222010  0.407967  2.627972 -0.646625  0.315224 -1.256556  0.391020   
2   -0.912279  0.140581  1.604592 -0.358110  0.241409 -0.942373 -0.056845   
3    1.112461  0.366872  1.253339 -0.776183  1.184850  0.186864 -0.652759   
4   -1.042800  0.325330  1.010588 -0.207308  0.635252 -0.262099 -0.549687   
..        ...       ...       ...       ...       ...       ...       ...   
745 -0.252621 -0.460511 -0.677400  0.723989  0.473791  0.021910 -0.491305   
746 -0.246324 -1.176413 -0.960008  0.659857  0.400619  0.516162  0.370860   
747  0.264746 -0.760078  0.543856 -0.293179  0.149160 -0.151330  0.246407   
748  0.557539  0.259147  0.130087  0.601868 -0.108343  1.448241 -0.212337   
749 -0.679785 -0.396586 -0.003415 -0.385927 -0.184637 -0.443110 -0.699789   

          7         8         9    ...       166       167       168  \
0   -0.188429  0.880772  0.985548  ... -1.641943 -0.176763  1.133432   
1    0.219483  0.860567  1.174878  ... -0.302797 -0.289969  0.388009   
2   -0.659134  0.356959  0.215741  ... -1.379001  0.003627 -0.015949   
3   -0.739469  1.035244  1.924699  ... -0.428502  0.270301  0.280280   
4    0.702037  0.377281  0.538637  ... -1.619954  0.394104  1.521806   
..        ...       ...       ...  ...       ...       ...       ...   
745 -1.210693 -0.319138 -0.251740  ... -0.370226 -0.315825  0.757425   
746  0.430125  0.890452  0.118196  ...  1.344524  0.276500  1.021200   
747 -0.936890  1.103655 -0.161136  ...  0.777336 -0.459562 -0.263059   
748 -1.114008  1.933827 -0.574729  ...  0.131545  0.102886  0.320871   
749  0.170899  0.343282  1.000203  ... -0.680360  0.470844  1.549079   

          169       170       171       172       173       174       175  
0    0.786111  0.149253 -0.822809  0.648026 -0.645598 -1.070584  0.650088  
1    0.823880  0.975161 -0.846089 -0.201287  0.176235  0.326525  0.054524  
2   -0.475891  0.227348 -0.166000 -0.213037 -0.513933 -0.325998 -0.316061  
3   -0.670332 -0.044446  0.689758  0.308167 -0.512299 -0.680800  0.167529  
4    0.766298  0.136187  0.501297 -0.234312 -0.377410  0.562110 -0.048923  
..        ...       ...       ...       ...       ...       ...       ...  
745 -0.243151 -0.660508  0.552605 -0.058359 -0.444978 -1.390065 -0.231872  
746  1.583635 -0.425096 -0.746123  1.175396 -0.158778 -0.338413  0.949265  
747 -0.310094  0.328991  0.200051 -0.872118  1.629330  0.878083  0.402273  
748 -0.867468  0.410845 -1.157011 -0.063201  0.357032 -0.074011 -0.385341  
749  0.589145  0.566260  0.454782  0.692949  0.381028 -0.144886  0.632048  

[750 rows x 176 columns]

In [ ]:
label4_features = pd.DataFrame(data=x_test_remove, columns=[f'new_feature_{i+1}' for i in range(x_test_remove.shape[1])])
label4_features.insert(0,'Predicted labels before feature engineering',label_4_pred_before)
label4_features.insert(1,'Predicted labels after feature engineering', label_4_pred_after)
label4_features.insert(2,'No of new features', x_test_remove.shape[1])

In [ ]:
write_csv(label4_features,"label_4")